# Generated by Django 4.0.6 on 2022-10-14 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'ແຊດ',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_post', models.TimeField(auto_now_add=True)),
                ('dsp_post', models.TextField()),
                ('date_post', models.DateTimeField(auto_now_add=True)),
                ('image_post', models.ImageField(upload_to='media')),
                ('like_post', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'ໂພສ',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_status', models.CharField(max_length=60)),
                ('dsp_status', models.TextField()),
                ('date_status', models.DateTimeField(auto_now_add=True)),
                ('image_status', models.ImageField(upload_to='media')),
                ('update_status', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ສະຖານະ',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat_app.chat')),
            ],
            options={
                'verbose_name_plural': 'ຫມູ່',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='friends',
            field=models.ManyToManyField(related_name='myfriends', to='chat_app.friend'),
        ),
    ]
